### ISSUE TITLE
Runtime error: "VulkanHelper CORE: Failed to find memory type index for buffer info!"

### ISSUE THREAD

**Issue by TomClabault** [Zydak/Vulkan-Path-Tracer#1]
So I cloned with `--recursive`, created a `Vulture/lib/shaderc/` folder at the root of the repository as instructed in the README, ran `setup.bat`, opened the Visual Studio solution and built `PathTracer`

First issue is that I got some `cannot find lib/shaderc/shadercDebug.lib` linker error. I moved the `shadercRelease.lib` and `shadercDebug.lib` from my `Vulture/lib/shaderc/` into `Vulkan-Helper/lib/shaderc` and this now seems to link properly.

The app starts and then throws that runtime error after a few seconds of loading stuff:

![image](https://github.com/user-attachments/assets/ff19a3f0-5d1a-4bf1-8595-cf29b9e46d5e)

Any idea what could be the issue? Also, is my setup with the `.lib` files correct? It seems to deviate from what the README says but it links fine after all...

**Comment by Zydak** [comment]
The build issue you're encountering is because I switched the name from `Vulture` to `Vulkan-Helper` recently but forgot to edit the README. Sorry about the libraries, right now, I'm in the process of converting everything from GLSL to Slang/HLSL and that entails adding a couple of libraries to the project, so the build process is one big mess. I'll fix that alongside the README as soon as possible. And as for the runtime error, it seems that VMA can't find the requested memory type. I'll also look into that, but I can't seem to reproduce this bug, and I'm not really sure what could cause it. My only idea is that, because I forgot to delete `allocInfo.usage = VMA_MEMORY_USAGE_AUTO;` line from `Device.cpp`, it can't find an appropriate memory type? I'd be grateful if you could try to run in debug mode and tell me what values exactly go into `vmaFindMemoryTypeIndexForBufferInfo()` in `Device.cpp`.

**Comment by Zydak** [comment]
Hm, that looks about right. The error is thrown when trying to find a memory type with the `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` flags, which, according to [this](https://vulkan.gpuinfo.org/listdevicescoverage.php?memorytype=6&platform=windows), should be supported on your 7900 XTX. If I am correct in assuming that on your PC `VK_ERROR_FEATURE_NOT_PRESENT` is returned on line `15004` in `vk_mem_alloc.h`, then, if it's not too much to ask, I’d need more information on what exactly is happening there. More specifically, what `memoryTypeBits` (line `14957`) are supported and the contents of `m_MemProps`. It just seems like VMA doesn't set `*pMemoryTypeIndex` (line `14994) to anything which causes the crash.

**Comment by TomClabault** [comment]
> If I am correct in assuming that on your PC VK_ERROR_FEATURE_NOT_PRESENT is returned on line 15004 in vk_mem_alloc.h
Correct.

> what memoryTypeBits (line 14957) are supported
![image](https://github.com/user-attachments/assets/8a7e43ba-f675-43ab-bda7-3c08482d675a)

`m_MemProps` at line 15004:
![image](https://github.com/user-attachments/assets/7e7630ce-9131-41ed-bcd9-7b920eba53b0)

**Comment by TomClabault** [comment]
Ok so pulling and recompiling now gives `memoryTypeBits = 17` instead of 1 but line 15004 still returns ``VK_ERROR_FEATURE_NOT_PRESENT

**Comment by TomClabault** [comment]
Here is  the output:

```
[20:30:58] VulkanHelper CORE: memory type bits[0] - 255
[20:30:58] VulkanHelper CORE: memory type bits[1] - 255
[20:30:58] VulkanHelper CORE: memory type bits[2] - 255
[20:30:58] VulkanHelper CORE: memory type bits[3] - 255
[20:30:58] VulkanHelper CORE: memory type bits[4] - 255
[20:30:58] VulkanHelper CORE: memory type bits[5] - 255
[20:30:58] VulkanHelper CORE: memory type bits[6] - 255
[20:30:58] VulkanHelper CORE: memory type bits[7] - 255
[20:30:58] VulkanHelper CORE: memory type bits[0] - 17
[20:30:58] VulkanHelper CORE: memory type bits[1] - 17
[20:30:58] VulkanHelper CORE: memory type bits[2] - 17
[20:30:58] VulkanHelper CORE: memory type bits[3] - 17
[20:30:58] VulkanHelper CORE: memory type bits[4] - 17
[20:30:58] VulkanHelper CORE: memory type bits[5] - 17
[20:30:58] VulkanHelper CORE: memory type bits[6] - 17
[20:30:58] VulkanHelper CORE: memory type bits[7] - 17
```

**Comment by Zydak** [comment]
Ok, so I think that for whatever reason on AMD only `DEVICE_LOCAL` memory is exportable. I pushed some changes, so if you could just pull and run it, that would be great.

**Comment by TomClabault** [comment]
Okay, that fixes it, awesome! There's still some more runtime errors coming after that about 
`VL_CORE_RETURN_ASSERT(cudaImportExternalSemaphore(&m_Semaphore.Cu, &externalSemaphoreHandleDesc), 0, "Importing External Semaphore Failed")`, Denoiser.cpp:393

I'll open another issue to keep things separate since this seems unrelated to the current issue.
