### ISSUE TITLE
cudaImportExternalSemaphore fails to import the semaphore on AMD GPU

### ISSUE THREAD

**Issue by TomClabault** [Zydak/Vulkan-Path-Tracer#2]
Cloning the repo, compiling and running the app yields a runtime error in Denoiser.cpp:393

`VL_CORE_RETURN_ASSERT(cudaImportExternalSemaphore(&m_Semaphore.Cu, &externalSemaphoreHandleDesc), 0, "Importing External Semaphore Failed");`

This must be because I'm using an AMD GPU and there are references to CUDA in the code?

**Comment by Zydak** [comment]
Path tracer uses OptixDenoiser which is based on CUDA so there's not much I can do to make it run on AMD. All I can really do is just disable it when AMD GPU is detected. It shouldn't be too hard to do.

**Comment by Zydak** [comment]
[3cc5d38](https://github.com/Zydak/Vulkan-Path-Tracer/commit/3cc5d38f5826e3a21f5e86eceb9840596a925bb0) should fix this issue. Could you confirm that it's working?

**Comment by TomClabault** [comment]
![Render19](https://github.com/user-attachments/assets/5c8c8880-535a-4d2f-9c67-4e77e669c14a)

Yup, it is running now👍
