### ISSUE TITLE
Scenes other than cornellBox.gltf or .ptscene files do not seem to render correctly

### ISSUE THREAD

**Issue by TomClabault** [Zydak/Vulkan-Path-Tracer#4]
Starting the app opens up on the cornell box. All seems to be good here.

However, trying to load another scene using the "Scene Editor" panel show black renders for all the other scenes (except the .ptscene scenes which work fine and cornellBox.gltf which also works fine). Any other scene gives a black render:

Dragon.obj:
![image](https://github.com/user-attachments/assets/64b9fc7c-66a6-4afd-9827-501f22867fcb)

Mustang.gltf:
![image](https://github.com/user-attachments/assets/05f3fee1-1eaa-4284-9378-a22ab2ef6e09)

I added one of my own scene to the assets folder and it  also started with a black render but after some time playing with the camera, trying to "find" the scene, I could eventually find it but the camera is not  orientated correctly:
![image](https://github.com/user-attachments/assets/f2791547-6ae4-48c8-a032-09ba0e8af46b)

Maybe this is all a camera problem after all? My custom scene ([the-white-room-low.gltf](https://github.com/TomClabault/HIPRT-Path-Tracer/tree/main/data/GLTFs)) does contain a camera in the GLTF file.

**Comment by Zydak** [comment]
It's not a camera problem. It's because there are no lights in the scene. You have to go into the `Environment Map Settings` tab and select anything. This way, there will be a light source in the scene. You can also select materials and make them emissive.

**Comment by TomClabault** [comment]
Oh yep indeed. Maybe an envmap should be loaded by default? Or a uniform sky color? Something that doesn't yield a totally black render could be more "intuitive".

**Comment by Zydak** [comment]
I guess that's a good idea. Maybe I'll also work on some "how to use" section in the readme.
